package com.chethan616.clearpdf.medical.domain

import com.chethan616.clearpdf.medical.model.MedicalDomain

/**
 * Unified translation output consumed by the PDF hover tooltip, dictionary sheet,
 * and academic sticky note generator.
 */
sealed interface TranslationResult {
    val sourceText: String
    val targetArabicText: String
    val domain: MedicalDomain
    val tierUsed: TranslationTier

    /**
     * Deterministic Tier 1 match returned from the embedded SQLite/FTS lexical database.
     * Contains exact clinical terms, Latin terminology, definitions, and domain classification.
     */
    data class LexicalMatch(
        override val sourceText: String,
        override val targetArabicText: String,
        override val domain: MedicalDomain,
        val latinName: String?,
        val subspecialty: String?,
        val definitionEn: String?,
        val definitionAr: String?,
        val sourceLexicon: String,
        val synonyms: List<String> = emptyList(),
        override val tierUsed: TranslationTier = TranslationTier.TIER_1_LEXICON,
        val matchedTerm: String? = null
    ) : TranslationResult

    /**
     * Contextual Tier 2 translation for complex sentences or paragraphs,
     * generated via an on-device Small Language Model (SLM).
     */
    data class ContextualSentence(
        override val sourceText: String,
        override val targetArabicText: String,
        override val domain: MedicalDomain,
        val clinicalNotes: String? = null,
        val highlightedEntities: List<ExtractedMedicalEntity> = emptyList(),
        override val tierUsed: TranslationTier = TranslationTier.TIER_2_ON_DEVICE_SLM
    ) : TranslationResult

    /**
     * Contextual Tier 2 translation representation with explicit confidence score.
     */
    data class ContextualMatch(
        override val sourceText: String,
        override val targetArabicText: String,
        override val domain: MedicalDomain = MedicalDomain.GENERAL_CLINICAL,
        val confidenceScore: Float = 0.95f,
        override val tierUsed: TranslationTier = TranslationTier.TIER_2_CONTEXTUAL_SLM,
        val clinicalNotes: String? = null,
        val highlightedEntities: List<ExtractedMedicalEntity> = emptyList()
    ) : TranslationResult

    /**
     * Signal to UI that full-sentence translation requires on-device model weights.
     */
    data class ModelDownloadRequired(
        override val sourceText: String,
        val modelSizeBytes: Long = 1_100_000_000L
    ) : TranslationResult {
        override val targetArabicText: String = ""
        override val domain: MedicalDomain = MedicalDomain.GENERAL_CLINICAL
        override val tierUsed: TranslationTier = TranslationTier.NONE
    }

    /**
     * Fallback when neither lexicon nor contextual engine can resolve a translation.
     */
    data class NotFound(
        override val sourceText: String,
        val reason: String = "No medical definition or contextual translation available."
    ) : TranslationResult {
        override val targetArabicText: String = ""
        override val domain: MedicalDomain = MedicalDomain.GENERAL_CLINICAL
        override val tierUsed: TranslationTier = TranslationTier.NONE
    }

    /**
     * Synthesized compound match generated by decomposing multi-word clinical phrases
     * (e.g. "enamel micro-hardness", "dentinal wall thickness", "pulpal blood flow")
     * into constituent head and modifier sub-tokens with Arabic grammatical synthesis.
     */
    data class DecomposedCompoundMatch(
        override val sourceText: String,
        val synthesizedArabicText: String,
        val subTokens: List<DecomposedSubToken>,
        val primaryDomain: MedicalDomain,
        override val tierUsed: TranslationTier = TranslationTier.TIER_1_LEXICON
    ) : TranslationResult {
        override val targetArabicText: String get() = synthesizedArabicText
        override val domain: MedicalDomain get() = primaryDomain
    }
}

/**
 * Constituent token of a decomposed multi-word clinical compound.
 */
data class DecomposedSubToken(
    val tokenEn: String,
    val translationAr: String,
    val domain: MedicalDomain,
    val latinRoot: String? = null,
    val definitionEn: String? = null,
    val definitionAr: String? = null
)

/**
 * Execution tier that serviced the translation query.
 */
enum class TranslationTier {
    TIER_1_LEXICON,
    TIER_2_ON_DEVICE_SLM,
    TIER_2_CONTEXTUAL_SLM,
    NONE
}

/**
 * Medical entity identified and extracted within a translated sentence or paragraph.
 */
data class ExtractedMedicalEntity(
    val englishTerm: String,
    val arabicEquivalent: String,
    val domain: MedicalDomain
)
